import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import ThemeProviders from "@/providers/ThemeProviders";
import SessionProviders from "@/providers/SessionProvider";
import { ToastProvider } from "@/providers/ToastProvider";
import QueryProvider from "@/providers/QueryProvider";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "LMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <QueryProvider>
          <ThemeProviders>
            <SessionProviders>
              <ToastProvider />
              {children}
            </SessionProviders>
          </ThemeProviders>
        </QueryProvider>
      </body>
    </html>
  );
}
